env: dev
size: s
services:
  api:      { capacity: spot, resources: { cpu: 500m, memory: 1Gi }, scaling: null, image: { tag: sha-PLACEHOLDER } }
  worker:   { resources: { cpu: 250m, memory: 512Mi }, scaling: null, image: { tag: sha-PLACEHOLDER } }
  migrator: { image: { tag: sha-PLACEHOLDER } }
